apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-configmap
  namespace: default
data:
  sidecarconfig.json: |
    {
      "spec": {
        "containers": [
          {
            "name": "nginx",
            "image": "nginx:1.21.0",
            "lifecycle": {
              "preStop": {
                "exec": {
                  "command": [
                    "/usr/sbin/nginx",
                    "-s",
                    "quit"
                  ]
                }
              }
            },
            "volumeMounts": [
              {
                "mountPath": "/etc/nginx/conf.d/",
                "name": "conf"
              }
            ]
          }
        ],
        "volumes": [
          {
            "name": "conf",
            "configMap": {
              "name": "nginx-config"
            }
          }
        ]
      }
    }