apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-configmap
  namespace: default
data:
  sidecarconfig.yaml: |
    containers:
    - name: nginx
      image: nginx:1.21.0
      imagePullPolicy: IfNotPresent